<a href="https://colab.research.google.com/github/bres/PytorchStudy/blob/main/pytorch_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Tensors basics
import torch

#create empty tensor
x =torch.empty(2, 2, 3) # 3 dimensions tensor --
print(x)

tensor([[[2.3778e-14, 0.0000e+00, 2.3168e-14],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 2.3262e-43],
         [2.3962e-43, 0.0000e+00, 6.0979e-38]]])


In [5]:
# create a tensor with 2 dimensions with random values
x = torch.rand(2, 2)
print(x)

tensor([[0.5397, 0.9463],
        [0.9356, 0.9482]])


In [6]:
# create a tensor with zeros
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [7]:
# create a tensor with ones
x =torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [8]:
# show data type
x = torch.ones(2, 2)
print(x.dtype)

torch.float32


In [9]:
# change the data type
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


In [10]:
# print the size of a tensor
x =torch.ones(2, 2)
print(x.size())

torch.Size([2, 2])


In [11]:
# construct a tensor from data
x =torch.tensor((2.5,0.1))
print(x)

tensor([2.5000, 0.1000])


In [35]:
# requires_grad argument
# this will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e this is a variable in your model that you want to optimize
x = torch.tensor([5.5,3],requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


**Operations on Tensors**

In [13]:
# operations between tensors
x =torch.rand(2,2)
y= torch.rand(2,2)
print(x)
print(y)
z =x+y
print(z)

tensor([[0.3051, 0.0516],
        [0.8534, 0.1333]])
tensor([[0.5766, 0.1058],
        [0.2959, 0.0449]])
tensor([[0.8817, 0.1574],
        [1.1493, 0.1782]])


In [14]:
# the same thing
z =torch.add(x,y)
print(z)

tensor([[0.8817, 0.1574],
        [1.1493, 0.1782]])


In [15]:
# in place addition  operation_ --> in place
y.add_(x)
print(y)

tensor([[0.8817, 0.1574],
        [1.1493, 0.1782]])


In [16]:
# subtract tensors
z =x-y
print(z)

tensor([[-0.5766, -0.1058],
        [-0.2959, -0.0449]])


In [18]:
# multiplacate tensors
z=x*y
print(z)

tensor([[0.2690, 0.0081],
        [0.9808, 0.0238]])


In [19]:
# divide tensors
z =x /y
print(z)

tensor([[0.3460, 0.3279],
        [0.7425, 0.7480]])


In [26]:
# slicing operations
x = torch.rand(5,3)
print(x)
print("")
# get all rows but the column zero
print(x[:,0])
print("")
# get row 1 but all columns
print(x[1,:])
# get one element
print("")
print(x[1,1])


tensor([[0.1073, 0.7545, 0.5473],
        [0.8550, 0.4545, 0.6535],
        [0.0216, 0.6678, 0.3110],
        [0.0157, 0.0044, 0.9585],
        [0.0710, 0.2799, 0.9646]])

tensor([0.1073, 0.8550, 0.0216, 0.0157, 0.0710])

tensor([0.8550, 0.4545, 0.6535])

tensor(0.4545)


In [27]:
# if i have only one element i can get it with this
print(x[1,1].item())

0.45447367429733276


In [30]:
# reshape a tensor
x =torch.rand(4,4)
print(x)
print("")
y =x.view(16) # NUMBER OF ELEMENTS MUST BE THE SAME WITH N*M
print(y)
# automatically detection of one dimension
print("")
y =x.view(-1,8) # -->2x8
print(y.size())



tensor([[0.8271, 0.9839, 0.9548, 0.4496],
        [0.2263, 0.7481, 0.5254, 0.3600],
        [0.4618, 0.7221, 0.0458, 0.4798],
        [0.6974, 0.3745, 0.1968, 0.6963]])

tensor([0.8271, 0.9839, 0.9548, 0.4496, 0.2263, 0.7481, 0.5254, 0.3600, 0.4618,
        0.7221, 0.0458, 0.4798, 0.6974, 0.3745, 0.1968, 0.6963])

torch.Size([2, 8])


**NumPy**
converting from tensor to a numpy and vice versa


In [32]:
# converting from tensor to a numpy
import numpy as np
a =torch.ones(5)
print(a)
print("")
b =a.numpy()
print(b)
print(type(b))
#sos
#if the tensor is on cpu and we change the tensor also changes the numpy
a.add_(1)
print(a)
print(b)


tensor([1., 1., 1., 1., 1.])

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
# converting from numpy to a tensor
a =np.ones(5)
print(a)
print("")
b =torch.from_numpy(a)
print(b)
print(type(b))


[1. 1. 1. 1. 1.]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


GPU support
By default all tensors are created on the CPU.But we can also move them to the GPU(if it's available), or create them directly on the GPU.

In [37]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device) # move tensors to GPU device -CPU device
#x = x.to('cpu')
#x = x.to('cuda')

x =torch.rand(2,2, device=device) # or directly crete them on GPU
print(x)

tensor([[0.4101, 0.4172],
        [0.6124, 0.7366]])


2.Autograd
The autograd package provides automatic differentiation for all operations on Tensors.Generally speaking, torch.autograd is an engine for computing the vector -Jacobian product.It computes partiedl derivatives while applying the chain rule.
**Set requires_grad =True;**


In [38]:
import torch
# requires_grad = True ->tracks all operations on the tensor.
x = torch.randn(3,requires_grad=True)
y = x+2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn:reference a Function that has created the Tensor
print(x)
print(y)
print(y.grad_fn)

tensor([-0.8054, -0.6790, -0.0780], requires_grad=True)
tensor([1.1946, 1.3210, 1.9220], grad_fn=<AddBackward0>)


In [40]:
# do more operations on y
z = y*y*3
print(z)
z = z.mean()
print(z)

tensor([ 4.2812,  5.2351, 11.0819], grad_fn=<MulBackward0>)
tensor(6.8661, grad_fn=<MeanBackward0>)


In [41]:
# Lets compute the gradients with backpropagation
# when we finish our computation we can call. backward() and have all the gradients computed automatically.
# The gradient for this tensor will be accumulated into .grad attribute.
# It is the partial derivative of the function with respect to the tensor

print (x.grad)
z.backward()
print(x.grad) # dz/dx

# Careful!!! backward() accumulates the gradient for this tensor into .grad attribute.
# We need to be careful during optimization !!! optimizer.zero_grad() --> empty the gradient results

None
tensor([2.3892, 2.6420, 3.8439])


**Stop a tensor from tracking history:**
For example during the training when we want to update our weights,or after training during ecaluation.These operations should not be part of the gradient computation.To prevent this we can use:


*   x.requires_grad_(False)

*   x.detach()

*   wrap in with torch.no_grad():








In [44]:
# requires_grad (...) changes an existing flag in-place.
a = torch.randn(2,2)
print(a)
print("")
print(a.requires_grad)
print("")
a.requires_grad_(True)
print(a.requires_grad)
print("")

tensor([[ 1.1682, -0.8116],
        [-0.5640, -1.5533]])

False

True



In [46]:
# detach(): get a new tensor with the same conetnt but no gradient computation:
a = torch.randn(2,2,requires_grad=True)
b = a.detach()
print(a.requires_grad)
print(b.requires_grad)


True
False


In [48]:
# wrap in 'with torch.no_grad():'
a = torch.randn(2,2,requires_grad=True)
print(a.requires_grad)
print("")
with torch.no_grad():
  b = a ** 2
  print(b.requires_grad)


True

False


**Gradient Descent Autograd**
Linear Regression example:
# f(x) = w * x +b
here: f(x) = 2 * x

In [49]:
import torch
# Linear regression
# f = w * x + b
# here : f = 2 * x
X = torch.tensor([1, 2, 3, 3, 5, 6, 7, ], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8, 10, 12, 14, ], dtype=torch.float32)

w = torch.tensor(0.0,dtype=torch.float32, requires_grad=True)

# model output
def forward(x):
  return w * x

# loss = MSE
def loss(y,y_predicted):
  return ((y_predicted-y)**2).mean()

X_test = 5.0
print(f'Prediction before training: f({X_test}) = {forward(X_test).item():.3f}')



Prediction before training: f(5.0) = 0.000


In [54]:
# Training
learning_rate = 0.01
n_epochs = 100

for epoch in range(n_epochs):
  # predict = forward pass
  y_pred = forward(X)

  # loss
  l = loss(Y,y_pred)

  # calculate
  l.backward() # dl/dw

  # update weights
  with torch.no_grad():
    w -= learning_rate * w.grad

  # zero gradients--epty the gradients before next iteration
  w.grad.zero_()

  if (epoch+1) % 10 == 0:
    print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.3f}')

print(f'Prediction after training: f({X_test}) = {forward(X_test).item():.3f}')

epoch 10: w = 2.045, loss = 0.533
epoch 20: w = 2.045, loss = 0.533
epoch 30: w = 2.045, loss = 0.533
epoch 40: w = 2.045, loss = 0.533
epoch 50: w = 2.045, loss = 0.533
epoch 60: w = 2.045, loss = 0.533
epoch 70: w = 2.045, loss = 0.533
epoch 80: w = 2.045, loss = 0.533
epoch 90: w = 2.045, loss = 0.533
epoch 100: w = 2.045, loss = 0.533
Prediction after training: f(5.0) = 10.226
