<a href="https://colab.research.google.com/github/bres/PytorchStudy/blob/main/pytorch_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Tensors basics
import torch

#create empty tensor
x =torch.empty(2, 2, 3) # 3 dimensions tensor --
print(x)

tensor([[[2.3778e-14, 0.0000e+00, 2.3168e-14],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 2.3262e-43],
         [2.3962e-43, 0.0000e+00, 6.0979e-38]]])


In [5]:
# create a tensor with 2 dimensions with random values
x = torch.rand(2, 2)
print(x)

tensor([[0.5397, 0.9463],
        [0.9356, 0.9482]])


In [6]:
# create a tensor with zeros
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [7]:
# create a tensor with ones
x =torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [8]:
# show data type
x = torch.ones(2, 2)
print(x.dtype)

torch.float32


In [9]:
# change the data tyoe
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


In [10]:
# print the size of a tensor
x =torch.ones(2, 2)
print(x.size())

torch.Size([2, 2])


In [11]:
# construct a tensor from data
x =torch.tensor((2.5,0.1))
print(x)

tensor([2.5000, 0.1000])


In [13]:
# operations between tensors
x =torch.rand(2,2)
y= torch.rand(2,2)
print(x)
print(y)
z =x+y
print(z)

tensor([[0.3051, 0.0516],
        [0.8534, 0.1333]])
tensor([[0.5766, 0.1058],
        [0.2959, 0.0449]])
tensor([[0.8817, 0.1574],
        [1.1493, 0.1782]])


In [14]:
# the same thing
z =torch.add(x,y)
print(z)

tensor([[0.8817, 0.1574],
        [1.1493, 0.1782]])


In [15]:
# in place addition  operation_ --> in place
y.add_(x)
print(y)

tensor([[0.8817, 0.1574],
        [1.1493, 0.1782]])


In [16]:
# subtract tensors
z =x-y
print(z)

tensor([[-0.5766, -0.1058],
        [-0.2959, -0.0449]])


In [18]:
# multiplacate tensors
z=x*y
print(z)

tensor([[0.2690, 0.0081],
        [0.9808, 0.0238]])


In [19]:
# divide tensors
z =x /y
print(z)

tensor([[0.3460, 0.3279],
        [0.7425, 0.7480]])


In [26]:
# slicing operations
x = torch.rand(5,3)
print(x)
print("")
# get all rows but the column zero
print(x[:,0])
print("")
# get row 1 but all columns
print(x[1,:])
# get one element
print("")
print(x[1,1])


tensor([[0.1073, 0.7545, 0.5473],
        [0.8550, 0.4545, 0.6535],
        [0.0216, 0.6678, 0.3110],
        [0.0157, 0.0044, 0.9585],
        [0.0710, 0.2799, 0.9646]])

tensor([0.1073, 0.8550, 0.0216, 0.0157, 0.0710])

tensor([0.8550, 0.4545, 0.6535])

tensor(0.4545)


In [27]:
# if i have only one element i can get it with this
print(x[1,1].item())

0.45447367429733276


In [30]:
# reshape a tensor
x =torch.rand(4,4)
print(x)
print("")
y =x.view(16) # NUMBER OF ELEMENTS MUST BE THE SAME WITH N*M
print(y)
# automatically detection of one dimension
print("")
y =x.view(-1,8) # -->2x8
print(y.size())



tensor([[0.8271, 0.9839, 0.9548, 0.4496],
        [0.2263, 0.7481, 0.5254, 0.3600],
        [0.4618, 0.7221, 0.0458, 0.4798],
        [0.6974, 0.3745, 0.1968, 0.6963]])

tensor([0.8271, 0.9839, 0.9548, 0.4496, 0.2263, 0.7481, 0.5254, 0.3600, 0.4618,
        0.7221, 0.0458, 0.4798, 0.6974, 0.3745, 0.1968, 0.6963])

torch.Size([2, 8])


In [32]:
# converting from tensor to a numpy
import numpy as np
a =torch.ones(5)
print(a)
print("")
b =a.numpy()
print(b)
print(type(b))
#sos
#if the tensor is on cpu and we change the tensor also changes the numpy
a.add_(1)
print(a)
print(b)


tensor([1., 1., 1., 1., 1.])

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
# converting from numpy to a tensor
a =np.ones(5)
print(a)
print("")
b =torch.from_numpy(a)
print(b)
print(type(b))


[1. 1. 1. 1. 1.]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [34]:
#check for gpu
if torch.cuda.is_available():
  device =torch.device("cuda")
  x =torch.ones(5, device=device)
  y =torch.ones(5)
  y =y.to(device)
  z =x+y
  print(z)